# Generated by Django 5.1.4 on 2024-12-15 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.EmailField(max_length=255)),
                ('recipient', models.EmailField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('date_received', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('replied', 'Replied')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField()),
                ('sentiment_label', models.CharField(max_length=50)),
                ('email_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='mail_app.emailmessage')),
            ],
        ),
    ]
