# Generated by Django 5.1.4 on 2024-12-15 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedresponse',
            name='email_message',
        ),
        migrations.DeleteModel(
            name='EmailMessage',
        ),
        migrations.DeleteModel(
            name='GeneratedResponse',
        ),
    ]
